collections:
  - name: "apartments"
    label: "Apartmani"
    files:
      - file: "data/apartments.json"
        label: "Apartmani"
        name: "apartments_list"
        fields:
          - label: "Apartmani"
            name: "items"
            widget: "list"
            fields:
              - { label: "Naziv", name: "title", widget: "string" }
              - label: "Slika"
                name: "image"
                widget: "image"
                choose_url: false
              - { label: "Ocjena", name: "ratingText", widget: "string" }
              - { label: "Airbnb link", name: "airbnbUrl", widget: "string" }
