backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "apartments"
    label: "Apartmani"
    files:
      - file: "data/apartments.json"
        label: "Lista apartmana"
        name: "apartments_list"
        fields:
          - label: "Apartmani"
            name: "items"
            widget: "list"
            fields:
              - { label: "Slug (npr p1)", name: "slug", widget: "string" }
              - { label: "Naziv", name: "title", widget: "string" }
              - { label: "Airbnb link", name: "airbnbUrl", widget: "string" }
              - { label: "Rating tekst", name: "ratingText", widget: "string", required: false }
              - { label: "Cover slika", name: "image", widget: "image", required: false }
              - label: "Galerija slika"
                name: "images"
                widget: "list"
                required: false
                field: { label: "Slika", name: "image", widget: "image" }
